/**
 * TypeScript enum representing all OGC API conformance class URIs.
 * Compiled from official OGC standards as of December 2025.
 * Usage: Use these string values to check conformance in API responses.
 */
export enum OGCAPIConformanceClass {
  // OGC API - Common - Part 1: Core
  COMMON_CORE = 'http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core',
  COMMON_LANDING_PAGE = 'http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/landing-page',
  COMMON_HTML = 'http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/html',
  COMMON_JSON = 'http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/json',
  COMMON_OAS30 = 'http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/oas30',

  // OGC API - Features - Part 1: Core
  FEATURES_CORE = 'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
  FEATURES_OAS30 = 'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
  FEATURES_HTML = 'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html',
  FEATURES_GEOJSON = 'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson',
  FEATURES_GMLSF0 = 'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0',
  FEATURES_GMLSF2 = 'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf2',

  // OGC API - Features - Part 5: Schemas
  FEATURES_SCHEMAS = 'http://www.opengis.net/spec/ogcapi-features-5/1.0/conf/schemas',

  // OGC API - Processes - Part 1: Core
  PROCESSES_CORE = 'http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/core',
  PROCESSES_OGC_PROCESS_DESCRIPTION = 'http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/ogc-process-description',
  PROCESSES_JSON = 'http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/json',
  PROCESSES_HTML = 'http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/html',
  PROCESSES_OAS30 = 'http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/oas30',
  PROCESSES_JOB_LIST = 'http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/job-list',
  PROCESSES_CALLBACK = 'http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/callback',
  PROCESSES_DISMISS = 'http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/dismiss',

  // OGC API - Tiles - Part 1: Core
  TILES_CORE = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core',
  TILES_TILESET = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset',
  TILES_TILESETS_LIST = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets-list',
  TILES_DATASET_TILESETS = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/dataset-tilesets',
  TILES_GEODATA_TILESETS = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geodata-tilesets',
  TILES_COLLECTIONS_SELECTION = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/collections-selection',
  TILES_DATETIME = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/datetime',
  TILES_OAS30 = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/oas30',
  TILES_XML = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/xml',
  TILES_PNG = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/png',
  TILES_JPEG = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/jpeg',
  TILES_TIFF = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tiff',
  TILES_NETCDF = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/netcdf',
  TILES_GEOJSON = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geojson',
  TILES_MVT = 'http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/mvt',

  // OGC API - Records - Part 1: Core
  RECORDS_CORE = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/core',
  RECORDS_RECORD_COLLECTION = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-collection',
  RECORDS_RECORD_CORE_QUERY_PARAMETERS = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core-query-parameters',
  RECORDS_RECORDS_API = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/records-api',
  RECORDS_SORTING = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/sorting',
  RECORDS_FILTERING = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/filtering',
  RECORDS_AUTODISCOVERY = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/autodiscovery',
  RECORDS_JSON = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/json',
  RECORDS_CRAWLABLE_CATALOG = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/crawlable-catalog',
  RECORDS_SEARCHABLE_CATALOG = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/searchable-catalog',
  RECORDS_SEARCHABLE_CATALOG_FILTERING = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/searchable-catalog-filtering',
  RECORDS_SEARCHABLE_CATALOG_SORTING = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/searchable-catalog-sorting',
  RECORDS_LOCAL_RESOURCES_CATALOG = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog',
  RECORDS_LOCAL_RESOURCES_CATALOG_QUERY_PARAMETERS = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog-query-parameters',
  RECORDS_LOCAL_RESOURCES_CATALOG_FILTERING = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog-filtering',
  RECORDS_LOCAL_RESOURCES_CATALOG_SORTING = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog-sorting',
  RECORDS_RECORD_CORE = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core',
  RECORDS_QUERY_PARAM_PROFILE = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/query-param-profile',
  RECORDS_HTML = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/html',
  RECORDS_OAS30 = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/oas30',
  RECORDS_CQL_FILTER = 'http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/cql-filter',

  // OGC API - Maps - Part 1: Core
  MAPS_CORE = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core',
  MAPS_TILESETS = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tilesets',
  MAPS_BACKGROUND = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/background',
  MAPS_COLLECTIONS_SELECTION = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collections-selection',
  MAPS_SCALING = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/scaling',
  MAPS_DISPLAY_RESOLUTION = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/display-resolution',
  MAPS_SPATIAL_SUBSETTING = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/spatial-subsetting',
  MAPS_DATETIME = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/datetime',
  MAPS_GENERAL_SUBSETTING = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/general-subsetting',
  MAPS_CRS = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/crs',
  MAPS_ORIENTATION = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/orientation',
  MAPS_PROJECTION = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/projection',
  MAPS_COLLECTION_MAP = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collection-map',
  MAPS_DATASET_MAP = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/dataset-map',
  MAPS_STYLED_MAP = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/styled-map',
  MAPS_PNG = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/png',
  MAPS_JPEG = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpeg',
  MAPS_JPEGXL = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpegxl',
  MAPS_TIFF = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tiff',
  MAPS_SVG = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/svg',
  MAPS_HTML = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/html',
  MAPS_API_OPERATIONS = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/api-operations',
  MAPS_CORS = 'http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/cors',

  // OGC API - Environmental Data Retrieval (EDR) - Part 1: Core
  EDR_CORE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/core',
  EDR_COLLECTIONS = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/collections',
  EDR_OAS30 = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/oas30',
  EDR_HTML = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/html',
  EDR_GEOJSON = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/geojson',
  EDR_JSON = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/json',
  EDR_EDR_GEOJSON = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr-geojson',
  EDR_COVJSON = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/covjson',
  EDR_QUERIES = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/queries',
  EDR_AREA = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/area',
  EDR_CUBE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/cube',
  EDR_TRAJECTORY = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/trajectory',
  EDR_CORRIDOR = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/corridor',
  EDR_LOCATIONS = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/locations',
  EDR_PARAMETER_NAME_DEFINITION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/rc-parameter-name-definition',
  EDR_PARAMETER_NAME_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/rc-parameter-name-response',
  EDR_CRS_DEFINITION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/REQ_rc-crs-definition',
  EDR_CRS_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/REQ_rc-crs-response',
  EDR_F_DEFINITION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/rc-f-definition',
  EDR_F_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/collections/rc-f-response',
  EDR_COORDS_DEFINITION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/rc-coords-definition',
  EDR_COORDS_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/rc-coords-response',
  EDR_Z_DEFINITION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/rc-z-definition',
  EDR_Z_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/rc-z-response',
  EDR_CUBE_Z_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/rc-cube-z-response',
  EDR_CORRIDOR_WIDTH_DEFINITION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/REQ_rc-corridor-width-definition',
  EDR_CORRIDOR_WIDTH_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/collections/REQ_rc-corridor-width-response',
  EDR_CORRIDOR_HEIGHT_DEFINITION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/REQ_rc-corridor-height-definition',
  EDR_CORRIDOR_HEIGHT_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/collections/REQ_rc-corridor-height-response',
  EDR_WIDTH_UNITS_DEFINITION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/REQ_rc-width-units-definition',
  EDR_WIDTH_UNITS_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/collections/REQ_rc-width-units-response',
  EDR_HEIGHT_UNITS_DEFINITION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/edr/REQ_rc-height-units-definition',
  EDR_HEIGHT_UNITS_RESPONSE = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/collections/rc-height-units-response',
  EDR_INSTANCES_METADATA_OPERATION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/instances/rc-md-op',
  EDR_INSTANCES_METADATA_SUCCESS = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/instances_rc-md-success',
  EDR_INSTANCE_SOURCE_METADATA_OPERATION = 'http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/instances/src-md-op',
}

export type OGCAPIConformanceItem =
  (typeof OGCAPIConformanceClass)[keyof typeof OGCAPIConformanceClass];
