import { describe, it, expect } from 'vitest';
import { rewriteAst, SUPPORTED_OPS } from '../../src/cql2/ast-rewrite.js';
import { createSentinels, addString } from '../../src/cql2/sentinels.js';
import { Cql2Error } from '../../src/cql2/errors.js';
import { translate, translateJson, codeOf } from './helpers.js';

const rewrite = (ast: unknown, sentinels = createSentinels()) =>
  rewriteAst(ast, { sentinels, maxDepth: 64 });

describe('unsupported operations', () => {
  it('rejects an unknown operation, naming it', () => {
    try {
      rewrite({ op: 'no_such_op', args: [{ property: 'a' }, 1] });
      expect.unreachable('should have thrown');
    } catch (err) {
      expect(err).toBeInstanceOf(Cql2Error);
      expect((err as Cql2Error).code).toBe('UNSUPPORTED_OP');
      expect((err as Cql2Error).message).toContain('no_such_op');
    }
  });

  it('rejects an unknown operation nested inside a supported one', () => {
    expect(
      codeOf(() =>
        rewrite({ op: 'and', args: [{ op: '=', args: [{ property: 'a' }, 1] }, { op: 'bad', args: [] }] })
      )
    ).toBe('UNSUPPORTED_OP');
  });

  it('rejects through the full translator, not just the pass', () => {
    expect(codeOf(() => translateJson({ op: 'my_udf', args: [{ property: 'a' }, 1] }))).toBe(
      'UNSUPPORTED_OP'
    );
  });

  it('accepts an operation named in additionalOps', () => {
    expect(() =>
      rewriteAst({ op: 'my_udf', args: [{ property: 'a' }] }, {
        sentinels: createSentinels(),
        additionalOps: ['my_udf'],
        maxDepth: 64,
      })
    ).not.toThrow();
  });

  it('covers every operation the translator is expected to handle', () => {
    for (const op of ['and', 'or', 'not', '=', 'like', 'between', 'in', 'isNull', 'casei', 'accenti', 'bbox']) {
      expect(SUPPORTED_OPS.has(op), op).toBe(true);
    }
    // All fifteen Allen relations, verified against to_ducksql().
    const temporal = [...SUPPORTED_OPS].filter((op) => op.startsWith('t_'));
    expect(temporal).toHaveLength(15);
    const spatial = [...SUPPORTED_OPS].filter((op) => op.startsWith('s_'));
    expect(spatial).toHaveLength(8);
  });

  it('rejects nesting deeper than maxDepth', () => {
    let deep: unknown = { op: '=', args: [{ property: 'a' }, 1] };
    for (let i = 0; i < 70; i++) deep = { op: 'not', args: [deep] };

    expect(codeOf(() => rewrite(deep))).toBe('PARSE_ERROR');
  });
});

describe('a_equals becomes set equality', () => {
  it('rewrites to containment in both directions', () => {
    const result = rewrite({ op: 'a_equals', args: [{ property: 'tags' }, ['eu']] });

    expect(result).toEqual({
      op: 'and',
      args: [
        { op: 'a_contains', args: [{ property: 'tags' }, ['eu']] },
        { op: 'a_contains', args: [['eu'], { property: 'tags' }] },
      ],
    });
  });

  it('produces list_has_all both ways in the final SQL', () => {
    const result = translateJson({ op: 'a_equals', args: [{ property: 'tags' }, ['eu']] });

    expect(result.sql.match(/list_has_all/g)).toHaveLength(2);
    // Generated by upstream from the rewritten AST — no pattern-matching on SQL.
    expect(result.sql).not.toContain('= ARRAY');
  });

  it('rejects the wrong argument count', () => {
    expect(codeOf(() => rewrite({ op: 'a_equals', args: [{ property: 'tags' }] }))).toBe(
      'PARSE_ERROR'
    );
  });

  it('leaves the other array operations alone', () => {
    const ast = { op: 'a_contains', args: [{ property: 'tags' }, ['eu']] };

    expect(rewrite(ast)).toEqual(ast);
  });
});

describe('unbounded interval bounds', () => {
  it('resolves a lower bound to -infinity by position', () => {
    const sentinels = createSentinels();
    const lower = addString(sentinels, '..');
    const upper = addString(sentinels, '2021-01-01T00:00:00Z');

    rewrite({ op: 't_intersects', args: [{ property: 'ts' }, { interval: [lower, upper] }] }, sentinels);

    expect(sentinels.strings).toEqual(['-infinity', '2021-01-01T00:00:00Z']);
  });

  it('resolves an upper bound to infinity by position', () => {
    const sentinels = createSentinels();
    const lower = addString(sentinels, '2020-01-01T00:00:00Z');
    const upper = addString(sentinels, '..');

    rewrite({ op: 't_intersects', args: [{ property: 'ts' }, { interval: [lower, upper] }] }, sentinels);

    expect(sentinels.strings).toEqual(['2020-01-01T00:00:00Z', 'infinity']);
  });

  it('leaves a bound that is a real timestamp alone', () => {
    const sentinels = createSentinels();
    const bound = addString(sentinels, '2020-01-01T00:00:00Z');

    rewrite({ op: 't_intersects', args: [{ property: 'ts' }, { interval: [bound, bound] }] }, sentinels);

    expect(sentinels.strings).toEqual(['2020-01-01T00:00:00Z']);
  });

  it('resolves through the full translator, from text', () => {
    expect(translate("T_INTERSECTS(ts, INTERVAL('..', '2021-01-01T00:00:00Z'))").params).toContain(
      '-infinity'
    );
    expect(translate("T_INTERSECTS(ts, INTERVAL('2020-01-01T00:00:00Z', '..'))").params).toContain(
      'infinity'
    );
  });

  it('does not touch a ".." used as an ordinary value', () => {
    expect(translate("name = '..'").params).toEqual(['..']);
  });
});

describe('structure is otherwise preserved', () => {
  it('leaves a geometry untouched', () => {
    const ast = {
      op: 's_intersects',
      args: [{ property: 'geom' }, { type: 'Point', coordinates: [1, 2] }],
    };

    expect(rewrite(ast)).toEqual(ast);
  });

  it('leaves scalars and nested logic untouched', () => {
    const ast = {
      op: 'and',
      args: [
        { op: '>', args: [{ property: 'pop' }, 1000] },
        { op: 'or', args: [{ op: 'isNull', args: [{ property: 'name' }] }, true] },
      ],
    };

    expect(rewrite(ast)).toEqual(ast);
  });
});
